### ISSUE TITLE
Strona zapisów ma różne dziwne problemy...

### ISSUE THREAD

**Issue by ziomciopoziomcio** [ziomciopoziomcio/TUL-HTML-project#2]
Z jakiegoś powodu, JS nie działa, myślę że to jest problem z importowaniem skryptów ale idk
Nie jest to aż tak pilne, bo z jakiegoś powodu to trochę samo podpowiada błędy w formularzu xD

**Comment by ziomciopoziomcio** [comment]
Okazuje się, że pierwsza funkcja blokowała drugą

**Comment by ziomciopoziomcio** [comment]
Zdaje się, że tym razem funkcja do walidacji danych blokuje funkcje od menu

**Comment by ninsson** [comment]
dropdown menu w zakładce zapisy jest inne niż w reszcie zakładek i na stronie głównej i trzeba zmienić
