### ISSUE TITLE
problem z powrotem do indexu z innych podstron

### ISSUE THREAD

**Issue by HASZYSZY** [ziomciopoziomcio/TUL-HTML-project#22]
po przejsciu na podstrone do indexu wyswietla sie komunikat Cannot GET /pages/index.html

**Comment by ziomciopoziomcio** [comment]
![image](https://github.com/ziomciopoziomcio/TUL-HTML-project/assets/60813479/2e230a3a-d386-4b3a-8bc3-92289e2e050a)
Adres strony: https://ziomciopoziomcio.github.io/TUL-HTML-project/pages/index.html
Adres oczekiwany: https://ziomciopoziomcio.github.io/TUL-HTML-project/ lub https://ziomciopoziomcio.github.io/TUL-HTML-project/index.html
